const title = "Share We?";
const CHUNK_SIZE = 16384;
const MINIMUM_EDGE_VERSION = 79;
const MINIMUM_FIREFOX_VERSION = 44;
const MINIMUM_OPR_VERSION = 43;
const MINIMUM_SAFARI_VERSION = 11;
const MINIMUM_CHROME_VERSION = 56;
const MINIMUM_SAMSUNGBROWSER_VERSION = 4;

export {
  CHUNK_SIZE,
  MINIMUM_EDGE_VERSION,
  MINIMUM_FIREFOX_VERSION,
  MINIMUM_OPR_VERSION,
  MINIMUM_SAFARI_VERSION,
  MINIMUM_CHROME_VERSION,
  MINIMUM_SAMSUNGBROWSER_VERSION,
};

export default title;
